'use client';

const JobData = [
  {
    id: 1,
    companyName: "Google India",
    jobTitle: "Frontend Developer",
    location: "Bangalore",
    stipend: "13.5 LPA CTC",
    requiredSkills: ["JavaScript", "React", "HTML"],
    jobType: "Remote",
    description: "Develop and maintain user-facing features using React and modern JavaScript.",
    dateOfPost: "2025-07-02",
    experienceRequired: 1
  },
  {
    id: 2,
    companyName: "TCS",
    jobTitle: "Backend Developer",
    location: "Chennai",
    stipend: "45.1 LPA CTC",
    requiredSkills: ["Node.js", "Express", "MongoDB"],
    jobType: "Remote",
    description: "Build and optimize scalable backend systems and RESTful APIs.",
    dateOfPost: "2025-07-01",
    experienceRequired: 3
  },
  {
    id: 3,
    companyName: "Infosys",
    jobTitle: "Data Scientist",
    location: "Pune",
    stipend: "9.8 LPA CTC",
    requiredSkills: ["Python", "SQL", "Pandas"],
    jobType: "On Site",
    description: "Analyze data and build predictive models for business solutions.",
    dateOfPost: "2025-06-30",
    experienceRequired: 2
  },
  {
    id: 4,
    companyName: "Wipro",
    jobTitle: "UI/UX Designer",
    location: "Bangalore",
    stipend: "33.0 LPA CTC",
    requiredSkills: ["Figma", "Adobe XD", "CSS"],
    jobType: "On Site",
    description: "Design intuitive user interfaces and improve user experience.",
    dateOfPost: "2025-06-29",
    experienceRequired: 4
  },
  {
    id: 5,
    companyName: "Amazon India",
    jobTitle: "Mobile App Developer",
    location: "Hyderabad",
    stipend: "24.7 LPA CTC",
    requiredSkills: ["Android", "Kotlin", "Java"],
    jobType: "On Site",
    description: "Develop mobile applications for Android and iOS platforms.",
    dateOfPost: "2025-06-28",
    experienceRequired: 2
  },
  {
    id: 6,
    companyName: "Flipkart",
    jobTitle: "Cloud Engineer",
    location: "Delhi",
    stipend: "19.4 LPA CTC",
    requiredSkills: ["AWS", "Linux", "Docker"],
    jobType: "Hybrid",
    description: "Manage cloud infrastructure and automate deployment processes.",
    dateOfPost: "2025-06-27",
    experienceRequired: 3
  },
  {
    id: 7,
    companyName: "Microsoft India",
    jobTitle: "AI/ML Engineer",
    location: "Mumbai",
    stipend: "27.8 LPA CTC",
    requiredSkills: ["TensorFlow", "Python", "Pandas"],
    jobType: "On Site",
    description: "Develop machine learning models and AI solutions.",
    dateOfPost: "2025-06-26",
    experienceRequired: 2
  },
  {
    id: 8,
    companyName: "Cognizant",
    jobTitle: "Full Stack Developer",
    location: "Bangalore",
    stipend: "17.2 LPA CTC",
    requiredSkills: ["JavaScript", "Node.js", "MongoDB"],
    jobType: "Remote",
    description: "Work on both frontend and backend development tasks.",
    dateOfPost: "2025-06-25",
    experienceRequired: 1
  },
  {
    id: 9,
    companyName: "Capgemini",
    jobTitle: "QA Tester",
    location: "Pune",
    stipend: "8.9 LPA CTC",
    requiredSkills: ["Selenium", "Java", "SQL"],
    jobType: "On Site",
    description: "Test software products to ensure quality and reliability.",
    dateOfPost: "2025-06-24",
    experienceRequired: 1
  },
  {
    id: 10,
    companyName: "HCL",
    jobTitle: "DevOps Engineer",
    location: "Hyderabad",
    stipend: "39.1 LPA CTC",
    requiredSkills: ["Kubernetes", "Linux", "Docker"],
    jobType: "Hybrid",
    description: "Automate and improve development and deployment pipelines.",
    dateOfPost: "2025-06-23",
    experienceRequired: 4
  },
  {
    id: 11,
    companyName: "Accenture",
    jobTitle: "Business Analyst",
    location: "Mumbai",
    stipend: "12.7 LPA CTC",
    requiredSkills: ["Excel", "SQL", "Power BI"],
    jobType: "Remote",
    description: "Analyze business processes and create data-driven reports.",
    dateOfPost: "2025-06-22",
    experienceRequired: 2
  },
  {
    id: 12,
    companyName: "IBM India",
    jobTitle: "Cybersecurity Engineer",
    location: "Pune",
    stipend: "25.0 LPA CTC",
    requiredSkills: ["Python", "Networking", "Linux"],
    jobType: "On Site",
    description: "Identify and mitigate security threats for enterprise systems.",
    dateOfPost: "2025-06-21",
    experienceRequired: 3
  },
  {
    id: 13,
    companyName: "Dell",
    jobTitle: "Network Engineer",
    location: "Chennai",
    stipend: "15.6 LPA CTC",
    requiredSkills: ["Networking", "Python", "Cisco"],
    jobType: "Remote",
    description: "Configure and maintain enterprise network infrastructure.",
    dateOfPost: "2025-06-20",
    experienceRequired: 2
  },
  {
    id: 14,
    companyName: "Oracle",
    jobTitle: "Database Administrator",
    location: "Hyderabad",
    stipend: "22.9 LPA CTC",
    requiredSkills: ["SQL", "Oracle", "Linux"],
    jobType: "Hybrid",
    description: "Maintain and optimize Oracle databases for performance.",
    dateOfPost: "2025-06-19",
    experienceRequired: 3
  },
  {
    id: 15,
    companyName: "SAP Labs",
    jobTitle: "ERP Consultant",
    location: "Bangalore",
    stipend: "29.0 LPA CTC",
    requiredSkills: ["SAP", "SQL", "Excel"],
    jobType: "On Site",
    description: "Support SAP consultants in implementing ERP solutions.",
    dateOfPost: "2025-06-18",
    experienceRequired: 4
  },
  {
    id: 16,
    companyName: "Adobe",
    jobTitle: "Web Designer",
    location: "Noida",
    stipend: "11.5 LPA CTC",
    requiredSkills: ["HTML", "CSS", "JavaScript"],
    jobType: "Remote",
    description: "Create visually appealing and responsive web designs.",
    dateOfPost: "2025-06-17",
    experienceRequired: 1
  },
  {
    id: 17,
    companyName: "Mindtree",
    jobTitle: "Cloud Support Engineer",
    location: "Pune",
    stipend: "14.0 LPA CTC",
    requiredSkills: ["AWS", "Azure", "Python"],
    jobType: "Hybrid",
    description: "Provide technical support for cloud-based solutions.",
    dateOfPost: "2025-06-16",
    experienceRequired: 2
  },
  {
    id: 18,
    companyName: "Zoho",
    jobTitle: "Product Manager",
    location: "Chennai",
    stipend: "41.2 LPA CTC",
    requiredSkills: ["Excel", "Communication", "Agile"],
    jobType: "On Site",
    description: "Assist in planning and executing product strategies.",
    dateOfPost: "2025-06-15",
    experienceRequired: 5
  },
  {
    id: 19,
    companyName: "Paytm",
    jobTitle: "Android Developer",
    location: "Noida",
    stipend: "10.9 LPA CTC",
    requiredSkills: ["Java", "Kotlin", "Android Studio"],
    jobType: "Remote",
    description: "Develop and test Android applications for Paytm.",
    dateOfPost: "2025-06-14",
    experienceRequired: 1
  },
  {
    id: 20,
    companyName: "Ola",
    jobTitle: "iOS Developer",
    location: "Bangalore",
    stipend: "18.5 LPA CTC",
    requiredSkills: ["Swift", "iOS", "Xcode"],
    jobType: "Hybrid",
    description: "Build and enhance ride-hailing mobile applications.",
    dateOfPost: "2025-06-13",
    experienceRequired: 2
  },
  {
    id: 21,
    companyName: "Swiggy",
    jobTitle: "Operations Analyst",
    location: "Hyderabad",
    stipend: "9.2 LPA CTC",
    requiredSkills: ["Excel", "Communication", "Logistics"],
    jobType: "On Site",
    description: "Support operations team in managing logistics and delivery.",
    dateOfPost: "2025-06-12",
    experienceRequired: 1
  },
  {
    id: 22,
    companyName: "Zomato",
    jobTitle: "Digital Marketing Specialist",
    location: "Delhi",
    stipend: "16.7 LPA CTC",
    requiredSkills: ["SEO", "Content Writing", "Analytics"],
    jobType: "Remote",
    description: "Plan and execute digital marketing campaigns.",
    dateOfPost: "2025-06-11",
    experienceRequired: 2
  },
  {
    id: 23,
    companyName: "BYJU'S",
    jobTitle: "Content Developer",
    location: "Bangalore",
    stipend: "7.5 LPA CTC",
    requiredSkills: ["Content Writing", "Editing", "Research"],
    jobType: "Hybrid",
    description: "Create and edit educational content for learning platforms.",
    dateOfPost: "2025-06-10",
    experienceRequired: 1
  },
  {
    id: 24,
    companyName: "Unacademy",
    jobTitle: "Video Editor",
    location: "Pune",
    stipend: "8.1 LPA CTC",
    requiredSkills: ["Premiere Pro", "After Effects", "Editing"],
    jobType: "On Site",
    description: "Edit and enhance educational videos for online courses.",
    dateOfPost: "2025-06-09",
    experienceRequired: 1
  },
  {
    id: 25,
    companyName: "Freshworks",
    jobTitle: "Customer Support Engineer",
    location: "Chennai",
    stipend: "13.3 LPA CTC",
    requiredSkills: ["Communication", "CRM", "Problem Solving"],
    jobType: "Remote",
    description: "Provide customer support and resolve technical queries.",
    dateOfPost: "2025-06-08",
    experienceRequired: 2
  },
  {
    id: 26,
    companyName: "RedBus",
    jobTitle: "Sales Executive",
    location: "Bangalore",
    stipend: "14.9 LPA CTC",
    requiredSkills: ["Sales", "Excel", "Negotiation"],
    jobType: "Hybrid",
    description: "Acquire new clients and manage relationships.",
    dateOfPost: "2025-06-07",
    experienceRequired: 2
  },
  {
    id: 27,
    companyName: "MakeMyTrip",
    jobTitle: "Travel Consultant",
    location: "Gurgaon",
    stipend: "11.8 LPA CTC",
    requiredSkills: ["Communication", "Travel", "Sales"],
    jobType: "On Site",
    description: "Assist customers in planning and booking travel itineraries.",
    dateOfPost: "2025-06-06",
    experienceRequired: 1
  },
  {
    id: 28,
    companyName: "Cleartrip",
    jobTitle: "Data Analyst",
    location: "Mumbai",
    stipend: "22.5 LPA CTC",
    requiredSkills: ["Excel", "SQL", "Python"],
    jobType: "Remote",
    description: "Analyze travel data and generate business insights.",
    dateOfPost: "2025-06-05",
    experienceRequired: 3
  },
  {
    id: 29,
    companyName: "UrbanClap",
    jobTitle: "Graphic Designer",
    location: "Delhi",
    stipend: "10.2 LPA CTC",
    requiredSkills: ["Photoshop", "Illustrator", "Creativity"],
    jobType: "Hybrid",
    description: "Design graphics and marketing materials.",
    dateOfPost: "2025-06-04",
    experienceRequired: 1
  },
  {
    id: 30,
    companyName: "OYO",
    jobTitle: "HR Executive",
    location: "Gurgaon",
    stipend: "13.7 LPA CTC",
    requiredSkills: ["HR", "Excel", "Communication"],
    jobType: "On Site",
    description: "Assist in recruitment and employee engagement activities.",
    dateOfPost: "2025-06-03",
    experienceRequired: 2
  },
  {
    id: 31,
    companyName: "Snapdeal",
    jobTitle: "Finance Analyst",
    location: "Delhi",
    stipend: "9.5 LPA CTC",
    requiredSkills: ["Finance", "Excel", "Accounting"],
    jobType: "Remote",
    description: "Support financial analysis and reporting.",
    dateOfPost: "2025-06-02",
    experienceRequired: 1
  },
  {
    id: 32,
    companyName: "Myntra",
    jobTitle: "Fashion Designer",
    location: "Bangalore",
    stipend: "11.9 LPA CTC",
    requiredSkills: ["Fashion", "Design", "Creativity"],
    jobType: "Hybrid",
    description: "Work on new fashion collections and concepts.",
    dateOfPost: "2025-06-01",
    experienceRequired: 2
  },
  {
    id: 33,
    companyName: "Reliance Jio",
    jobTitle: "Network Support Engineer",
    location: "Mumbai",
    stipend: "13.1 LPA CTC",
    requiredSkills: ["Networking", "Linux", "Communication"],
    jobType: "On Site",
    description: "Provide technical support for network infrastructure.",
    dateOfPost: "2025-05-31",
    experienceRequired: 2
  },
  {
    id: 34,
    companyName: "Bharti Airtel",
    jobTitle: "Marketing Specialist",
    location: "Delhi",
    stipend: "14.6 LPA CTC",
    requiredSkills: ["Marketing", "Excel", "Communication"],
    jobType: "Remote",
    description: "Execute marketing campaigns and analyze performance.",
    dateOfPost: "2025-05-30",
    experienceRequired: 2
  },
  {
    id: 35,
    companyName: "ICICI Bank",
    jobTitle: "Banking Officer",
    location: "Mumbai",
    stipend: "15.7 LPA CTC",
    requiredSkills: ["Banking", "Finance", "Excel"],
    jobType: "Hybrid",
    description: "Support banking operations and customer service.",
    dateOfPost: "2025-05-29",
    experienceRequired: 3
  },
  {
    id: 36,
    companyName: "Axis Bank",
    jobTitle: "Operations Analyst",
    location: "Pune",
    stipend: "8.7 LPA CTC",
    requiredSkills: ["Operations", "Excel", "Communication"],
    jobType: "On Site",
    description: "Assist in daily branch operations and process improvements.",
    dateOfPost: "2025-05-28",
    experienceRequired: 1
  },
  {
    id: 37,
    companyName: "HDFC Bank",
    jobTitle: "Risk Analyst",
    location: "Chennai",
    stipend: "10.8 LPA CTC",
    requiredSkills: ["Risk Analysis", "Finance", "Excel"],
    jobType: "Remote",
    description: "Analyze financial risks and prepare risk reports.",
    dateOfPost: "2025-05-27",
    experienceRequired: 2
  },
  {
    id: 38,
    companyName: "Kotak Mahindra",
    jobTitle: "Investment Analyst",
    location: "Hyderabad",
    stipend: "17.5 LPA CTC",
    requiredSkills: ["Investment", "Finance", "Excel"],
    jobType: "Hybrid",
    description: "Support investment advisors in portfolio management.",
    dateOfPost: "2025-05-26",
    experienceRequired: 3
  },
  {
    id: 39,
    companyName: "Tata Motors",
    jobTitle: "Mechanical Engineer",
    location: "Pune",
    stipend: "21.2 LPA CTC",
    requiredSkills: ["Mechanical", "CAD", "MATLAB"],
    jobType: "On Site",
    description: "Work on vehicle design and testing.",
    dateOfPost: "2025-05-25",
    experienceRequired: 3
  },
  {
    id: 40,
    companyName: "Mahindra",
    jobTitle: "Automobile Engineer",
    location: "Chennai",
    stipend: "23.9 LPA CTC",
    requiredSkills: ["Automobile", "CAD", "SolidWorks"],
    jobType: "Remote",
    description: "Design and model automobile components.",
    dateOfPost: "2025-05-24",
    experienceRequired: 3
  },
  {
    id: 41,
    companyName: "Bajaj Auto",
    jobTitle: "Production Engineer",
    location: "Pune",
    stipend: "12.8 LPA CTC",
    requiredSkills: ["Production", "Excel", "AutoCAD"],
    jobType: "Hybrid",
    description: "Support production planning and process optimization.",
    dateOfPost: "2025-05-23",
    experienceRequired: 2
  },
  {
    id: 42,
    companyName: "L&T",
    jobTitle: "Civil Engineer",
    location: "Mumbai",
    stipend: "20.1 LPA CTC",
    requiredSkills: ["Civil", "AutoCAD", "Excel"],
    jobType: "On Site",
    description: "Assist in site supervision and structural design.",
    dateOfPost: "2025-05-22",
    experienceRequired: 3
  },
  {
    id: 43,
    companyName: "Godrej",
    jobTitle: "Chemical Engineer",
    location: "Hyderabad",
    stipend: "9.0 LPA CTC",
    requiredSkills: ["Chemical", "Excel", "MATLAB"],
    jobType: "Remote",
    description: "Work on chemical process optimization and safety analysis.",
    dateOfPost: "2025-05-21",
    experienceRequired: 1
  },
  {
    id: 44,
    companyName: "Asian Paints",
    jobTitle: "Quality Analyst",
    location: "Chennai",
    stipend: "8.1 LPA CTC",
    requiredSkills: ["QA", "Excel", "Chemistry"],
    jobType: "Hybrid",
    description: "Test and ensure the quality of paint products.",
    dateOfPost: "2025-05-20",
    experienceRequired: 1
  },
  {
    id: 45,
    companyName: "ITC",
    jobTitle: "Food Technologist",
    location: "Kolkata",
    stipend: "15.9 LPA CTC",
    requiredSkills: ["Food Tech", "Excel", "Research"],
    jobType: "On Site",
    description: "Support food innovation team in developing new products.",
    dateOfPost: "2025-05-19",
    experienceRequired: 2
  },
  {
    id: 46,
    companyName: "Nestle",
    jobTitle: "Nutritionist",
    location: "Delhi",
    stipend: "13.8 LPA CTC",
    requiredSkills: ["Nutrition", "Research", "Excel"],
    jobType: "Remote",
    description: "Assist in nutritional research and product analysis.",
    dateOfPost: "2025-05-18",
    experienceRequired: 2
  },
  {
    id: 47,
    companyName: "Dabur",
    jobTitle: "Microbiologist",
    location: "Ghaziabad",
    stipend: "10.6 LPA CTC",
    requiredSkills: ["Microbiology", "Research", "Excel"],
    jobType: "Hybrid",
    description: "Conduct microbiological tests and quality checks.",
    dateOfPost: "2025-05-17",
    experienceRequired: 1
  },
  {
    id: 48,
    companyName: "Amul",
    jobTitle: "Dairy Technologist",
    location: "Anand",
    stipend: "11.4 LPA CTC",
    requiredSkills: ["Dairy Tech", "Excel", "Research"],
    jobType: "On Site",
    description: "Work with dairy team to improve processing and product quality.",
    dateOfPost: "2025-05-16",
    experienceRequired: 1
  },
  {
    id: 49,
    companyName: "Parle",
    jobTitle: "Food Safety Analyst",
    location: "Mumbai",
    stipend: "14.3 LPA CTC",
    requiredSkills: ["Food Safety", "Research", "Excel"],
    jobType: "Remote",
    description: "Assist in food safety audits and compliance.",
    dateOfPost: "2025-05-15",
    experienceRequired: 2
  },
  {
    id: 50,
    companyName: "Britannia",
    jobTitle: "Packaging Engineer",
    location: "Bangalore",
    stipend: "17.6 LPA CTC",
    requiredSkills: ["Packaging", "Design", "Excel"],
    jobType: "Hybrid",
    description: "Design and test new packaging solutions.",
    dateOfPost: "2025-05-14",
    experienceRequired: 2
  }
];

export default JobData;
