'use client';

const internshipData = [
  {
    id: 1,
    companyName: "Google India",
    jobTitle: "Frontend Developer Intern",
    location: "Bangalore",
    stipend: "6000 INR/month",
    requiredSkills: ["JavaScript", "React", "Node.js"],
    internshipType: "On Site",
    description: "Work with Google's frontend team to build scalable web interfaces using React and modern JavaScript.",
    dateOfPost: "2025-07-02"
  },
  {
    id: 2,
    companyName: "TCS",
    jobTitle: "Backend Developer Intern",
    location: "Hyderabad",
    stipend: "7000 INR/month",
    requiredSkills: ["React", "Node.js", "Python"],
    internshipType: "Remote",
    description: "Join TCS's backend team to develop and maintain robust server-side applications using Node.js and Python.",
    dateOfPost: "2025-07-01"
  },
  {
    id: 3,
    companyName: "Infosys",
    jobTitle: "Data Science Intern",
    location: "Mumbai",
    stipend: "8000 INR/month",
    requiredSkills: ["Node.js", "Python", "SQL"],
    internshipType: "Hybrid",
    description: "Assist in analyzing large datasets and building predictive models for business insights at Infosys.",
    dateOfPost: "2025-06-30"
  },
  {
    id: 4,
    companyName: "Wipro",
    jobTitle: "UI/UX Designer Intern",
    location: "Delhi",
    stipend: "9000 INR/month",
    requiredSkills: ["Python", "SQL", "Java"],
    internshipType: "On Site",
    description: "Contribute to designing user-friendly interfaces and improving user experiences for Wipro's digital products.",
    dateOfPost: "2025-06-29"
  },
  {
    id: 5,
    companyName: "Amazon India",
    jobTitle: "Mobile App Developer Intern",
    location: "Chennai",
    stipend: "10000 INR/month",
    requiredSkills: ["SQL", "Java", "C++"],
    internshipType: "Remote",
    description: "Develop and optimize mobile applications for Amazon India's e-commerce platform.",
    dateOfPost: "2025-06-28"
  },
  {
    id: 6,
    companyName: "Flipkart",
    jobTitle: "Cloud Engineer Intern",
    location: "Pune",
    stipend: "9500 INR/month",
    requiredSkills: ["AWS", "Python", "Linux"],
    internshipType: "Hybrid",
    description: "Support Flipkart's cloud infrastructure by automating deployments and monitoring systems.",
    dateOfPost: "2025-06-27"
  },
  {
    id: 7,
    companyName: "Microsoft India",
    jobTitle: "AI/ML Intern",
    location: "Bangalore",
    stipend: "12000 INR/month",
    requiredSkills: ["Python", "TensorFlow", "Pandas"],
    internshipType: "On Site",
    description: "Collaborate on AI/ML projects to develop intelligent solutions for Microsoft India's products.",
    dateOfPost: "2025-06-26"
  },
  {
    id: 8,
    companyName: "Cognizant",
    jobTitle: "Full Stack Developer Intern",
    location: "Kolkata",
    stipend: "8000 INR/month",
    requiredSkills: ["JavaScript", "Node.js", "MongoDB"],
    internshipType: "Remote",
    description: "Work on both frontend and backend development for web applications at Cognizant.",
    dateOfPost: "2025-06-25"
  },
  {
    id: 9,
    companyName: "Capgemini",
    jobTitle: "QA Tester Intern",
    location: "Noida",
    stipend: "7500 INR/month",
    requiredSkills: ["Selenium", "Java", "SQL"],
    internshipType: "On Site",
    description: "Test and ensure the quality of Capgemini's software products through automated and manual testing.",
    dateOfPost: "2025-06-24"
  },
  {
    id: 10,
    companyName: "HCL",
    jobTitle: "DevOps Intern",
    location: "Gurgaon",
    stipend: "8500 INR/month",
    requiredSkills: ["Docker", "Kubernetes", "Linux"],
    internshipType: "Hybrid",
    description: "Assist in automating deployment pipelines and managing cloud infrastructure at HCL.",
    dateOfPost: "2025-06-23"
  },
  {
    id: 11,
    companyName: "Accenture",
    jobTitle: "Business Analyst Intern",
    location: "Mumbai",
    stipend: "7000 INR/month",
    requiredSkills: ["Excel", "SQL", "Power BI"],
    internshipType: "Remote",
    description: "Analyze business processes and create data-driven reports for Accenture's clients.",
    dateOfPost: "2025-06-22"
  },
  {
    id: 12,
    companyName: "IBM India",
    jobTitle: "Cybersecurity Intern",
    location: "Pune",
    stipend: "9000 INR/month",
    requiredSkills: ["Python", "Networking", "Linux"],
    internshipType: "On Site",
    description: "Support IBM India's cybersecurity team in identifying and mitigating security threats.",
    dateOfPost: "2025-06-21"
  },
  {
    id: 13,
    companyName: "Dell",
    jobTitle: "Network Engineer Intern",
    location: "Chennai",
    stipend: "8000 INR/month",
    requiredSkills: ["Networking", "Python", "Cisco"],
    internshipType: "Remote",
    description: "Assist in configuring and maintaining Dell's enterprise network infrastructure.",
    dateOfPost: "2025-06-20"
  },
  {
    id: 14,
    companyName: "Oracle",
    jobTitle: "Database Admin Intern",
    location: "Hyderabad",
    stipend: "9500 INR/month",
    requiredSkills: ["SQL", "Oracle", "Linux"],
    internshipType: "Hybrid",
    description: "Maintain and optimize Oracle databases for high performance and reliability.",
    dateOfPost: "2025-06-19"
  },
  {
    id: 15,
    companyName: "SAP Labs",
    jobTitle: "ERP Consultant Intern",
    location: "Bangalore",
    stipend: "10000 INR/month",
    requiredSkills: ["SAP", "SQL", "Excel"],
    internshipType: "On Site",
    description: "Support SAP consultants in implementing and customizing ERP solutions.",
    dateOfPost: "2025-06-18"
  },
  {
    id: 16,
    companyName: "Adobe",
    jobTitle: "Web Designer Intern",
    location: "Noida",
    stipend: "8500 INR/month",
    requiredSkills: ["HTML", "CSS", "JavaScript"],
    internshipType: "Remote",
    description: "Create visually appealing and responsive web designs for Adobe's digital products.",
    dateOfPost: "2025-06-17"
  },
  {
    id: 17,
    companyName: "Mindtree",
    jobTitle: "Cloud Support Intern",
    location: "Pune",
    stipend: "9000 INR/month",
    requiredSkills: ["AWS", "Azure", "Python"],
    internshipType: "Hybrid",
    description: "Provide technical support for cloud-based solutions and troubleshoot issues at Mindtree.",
    dateOfPost: "2025-06-16"
  },
  {
    id: 18,
    companyName: "Zoho",
    jobTitle: "Product Manager Intern",
    location: "Chennai",
    stipend: "9500 INR/month",
    requiredSkills: ["Excel", "Communication", "Agile"],
    internshipType: "On Site",
    description: "Assist product managers in planning and executing product strategies at Zoho.",
    dateOfPost: "2025-06-15"
  },
  {
    id: 19,
    companyName: "Paytm",
    jobTitle: "Android Developer Intern",
    location: "Noida",
    stipend: "8000 INR/month",
    requiredSkills: ["Java", "Kotlin", "Android Studio"],
    internshipType: "Remote",
    description: "Develop and test Android applications for Paytm's mobile platform.",
    dateOfPost: "2025-06-14"
  },
  {
    id: 20,
    companyName: "Ola",
    jobTitle: "iOS Developer Intern",
    location: "Bangalore",
    stipend: "10000 INR/month",
    requiredSkills: ["Swift", "iOS", "Xcode"],
    internshipType: "Hybrid",
    description: "Work with Ola's iOS team to build and enhance ride-hailing mobile applications.",
    dateOfPost: "2025-06-13"
  },
  {
    id: 21,
    companyName: "Swiggy",
    jobTitle: "Operations Intern",
    location: "Hyderabad",
    stipend: "7000 INR/month",
    requiredSkills: ["Excel", "Communication", "Logistics"],
    internshipType: "On Site",
    description: "Support Swiggy's operations team in managing logistics and delivery processes.",
    dateOfPost: "2025-06-12"
  },
  {
    id: 22,
    companyName: "Zomato",
    jobTitle: "Digital Marketing Intern",
    location: "Delhi",
    stipend: "7500 INR/month",
    requiredSkills: ["SEO", "Content Writing", "Analytics"],
    internshipType: "Remote",
    description: "Assist in planning and executing digital marketing campaigns for Zomato.",
    dateOfPost: "2025-06-11"
  },
  {
    id: 23,
    companyName: "BYJU'S",
    jobTitle: "Content Developer Intern",
    location: "Bangalore",
    stipend: "8000 INR/month",
    requiredSkills: ["Content Writing", "Editing", "Research"],
    internshipType: "Hybrid",
    description: "Create and edit educational content for BYJU'S learning platforms.",
    dateOfPost: "2025-06-10"
  },
  {
    id: 24,
    companyName: "Unacademy",
    jobTitle: "Video Editor Intern",
    location: "Pune",
    stipend: "8500 INR/month",
    requiredSkills: ["Premiere Pro", "After Effects", "Editing"],
    internshipType: "On Site",
    description: "Edit and enhance educational videos for Unacademy's online courses.",
    dateOfPost: "2025-06-09"
  },
  {
    id: 25,
    companyName: "Freshworks",
    jobTitle: "Customer Support Intern",
    location: "Chennai",
    stipend: "7000 INR/month",
    requiredSkills: ["Communication", "CRM", "Problem Solving"],
    internshipType: "Remote",
    description: "Provide customer support and resolve queries for Freshworks clients.",
    dateOfPost: "2025-06-08"
  },
  {
    id: 26,
    companyName: "RedBus",
    jobTitle: "Sales Intern",
    location: "Bangalore",
    stipend: "7500 INR/month",
    requiredSkills: ["Sales", "Excel", "Negotiation"],
    internshipType: "Hybrid",
    description: "Support the sales team in acquiring new clients and managing relationships at RedBus.",
    dateOfPost: "2025-06-07"
  },
  {
    id: 27,
    companyName: "MakeMyTrip",
    jobTitle: "Travel Consultant Intern",
    location: "Gurgaon",
    stipend: "8000 INR/month",
    requiredSkills: ["Communication", "Travel", "Sales"],
    internshipType: "On Site",
    description: "Assist customers in planning and booking travel itineraries with MakeMyTrip.",
    dateOfPost: "2025-06-06"
  },
  {
    id: 28,
    companyName: "Cleartrip",
    jobTitle: "Data Analyst Intern",
    location: "Mumbai",
    stipend: "9000 INR/month",
    requiredSkills: ["Excel", "SQL", "Python"],
    internshipType: "Remote",
    description: "Analyze travel data and generate insights for Cleartrip's business strategies.",
    dateOfPost: "2025-06-05"
  },
  {
    id: 29,
    companyName: "UrbanClap",
    jobTitle: "Graphic Designer Intern",
    location: "Delhi",
    stipend: "8500 INR/month",
    requiredSkills: ["Photoshop", "Illustrator", "Creativity"],
    internshipType: "Hybrid",
    description: "Design creative graphics and marketing materials for UrbanClap's campaigns.",
    dateOfPost: "2025-06-04"
  },
  {
    id: 30,
    companyName: "OYO",
    jobTitle: "HR Intern",
    location: "Gurgaon",
    stipend: "7000 INR/month",
    requiredSkills: ["HR", "Excel", "Communication"],
    internshipType: "On Site",
    description: "Assist the HR team in recruitment and employee engagement activities at OYO.",
    dateOfPost: "2025-06-03"
  },
  {
    id: 31,
    companyName: "Snapdeal",
    jobTitle: "Finance Intern",
    location: "Delhi",
    stipend: "8000 INR/month",
    requiredSkills: ["Finance", "Excel", "Accounting"],
    internshipType: "Remote",
    description: "Support financial analysis and reporting for Snapdeal's finance department.",
    dateOfPost: "2025-06-02"
  },
  {
    id: 32,
    companyName: "Myntra",
    jobTitle: "Fashion Designer Intern",
    location: "Bangalore",
    stipend: "9000 INR/month",
    requiredSkills: ["Fashion", "Design", "Creativity"],
    internshipType: "Hybrid",
    description: "Work with Myntra's design team to create new fashion collections and concepts.",
    dateOfPost: "2025-06-01"
  },
  {
    id: 33,
    companyName: "Reliance Jio",
    jobTitle: "Network Support Intern",
    location: "Mumbai",
    stipend: "8500 INR/month",
    requiredSkills: ["Networking", "Linux", "Communication"],
    internshipType: "On Site",
    description: "Provide technical support for Reliance Jio's network infrastructure.",
    dateOfPost: "2025-05-31"
  },
  {
    id: 34,
    companyName: "Bharti Airtel",
    jobTitle: "Marketing Intern",
    location: "Delhi",
    stipend: "8000 INR/month",
    requiredSkills: ["Marketing", "Excel", "Communication"],
    internshipType: "Remote",
    description: "Assist in executing marketing campaigns and analyzing their performance at Airtel.",
    dateOfPost: "2025-05-30"
  },
  {
    id: 35,
    companyName: "ICICI Bank",
    jobTitle: "Banking Intern",
    location: "Mumbai",
    stipend: "9000 INR/month",
    requiredSkills: ["Banking", "Finance", "Excel"],
    internshipType: "Hybrid",
    description: "Support banking operations and customer service at ICICI Bank branches.",
    dateOfPost: "2025-05-29"
  },
  {
    id: 36,
    companyName: "Axis Bank",
    jobTitle: "Operations Intern",
    location: "Pune",
    stipend: "8500 INR/month",
    requiredSkills: ["Operations", "Excel", "Communication"],
    internshipType: "On Site",
    description: "Assist in daily branch operations and process improvements at Axis Bank.",
    dateOfPost: "2025-05-28"
  },
  {
    id: 37,
    companyName: "HDFC Bank",
    jobTitle: "Risk Analyst Intern",
    location: "Chennai",
    stipend: "8000 INR/month",
    requiredSkills: ["Risk Analysis", "Finance", "Excel"],
    internshipType: "Remote",
    description: "Analyze financial risks and prepare risk assessment reports for HDFC Bank.",
    dateOfPost: "2025-05-27"
  },
  {
    id: 38,
    companyName: "Kotak Mahindra",
    jobTitle: "Investment Intern",
    location: "Hyderabad",
    stipend: "9000 INR/month",
    requiredSkills: ["Investment", "Finance", "Excel"],
    internshipType: "Hybrid",
    description: "Support investment advisors in portfolio management and client research.",
    dateOfPost: "2025-05-26"
  },
  {
    id: 39,
    companyName: "Tata Motors",
    jobTitle: "Mechanical Engineer Intern",
    location: "Pune",
    stipend: "9500 INR/month",
    requiredSkills: ["Mechanical", "CAD", "MATLAB"],
    internshipType: "On Site",
    description: "Work with Tata Motors' engineering team on vehicle design and testing.",
    dateOfPost: "2025-05-25"
  },
  {
    id: 40,
    companyName: "Mahindra",
    jobTitle: "Automobile Engineer Intern",
    location: "Chennai",
    stipend: "10000 INR/month",
    requiredSkills: ["Automobile", "CAD", "SolidWorks"],
    internshipType: "Remote",
    description: "Assist in designing and modeling automobile components at Mahindra.",
    dateOfPost: "2025-05-24"
  },
  {
    id: 41,
    companyName: "Bajaj Auto",
    jobTitle: "Production Engineer Intern",
    location: "Pune",
    stipend: "9000 INR/month",
    requiredSkills: ["Production", "Excel", "AutoCAD"],
    internshipType: "Hybrid",
    description: "Support production planning and process optimization at Bajaj Auto.",
    dateOfPost: "2025-05-23"
  },
  {
    id: 42,
    companyName: "L&T",
    jobTitle: "Civil Engineer Intern",
    location: "Mumbai",
    stipend: "9500 INR/month",
    requiredSkills: ["Civil", "AutoCAD", "Excel"],
    internshipType: "On Site",
    description: "Assist in site supervision and structural design for L&T's civil projects.",
    dateOfPost: "2025-05-22"
  },
  {
    id: 43,
    companyName: "Godrej",
    jobTitle: "Chemical Engineer Intern",
    location: "Hyderabad",
    stipend: "9000 INR/month",
    requiredSkills: ["Chemical", "Excel", "MATLAB"],
    internshipType: "Remote",
    description: "Work on chemical process optimization and safety analysis at Godrej.",
    dateOfPost: "2025-05-21"
  },
  {
    id: 44,
    companyName: "Asian Paints",
    jobTitle: "Quality Analyst Intern",
    location: "Chennai",
    stipend: "8500 INR/month",
    requiredSkills: ["QA", "Excel", "Chemistry"],
    internshipType: "Hybrid",
    description: "Test and ensure the quality of paint products at Asian Paints' labs.",
    dateOfPost: "2025-05-20"
  },
  {
    id: 45,
    companyName: "ITC",
    jobTitle: "Food Technologist Intern",
    location: "Kolkata",
    stipend: "8000 INR/month",
    requiredSkills: ["Food Tech", "Excel", "Research"],
    internshipType: "On Site",
    description: "Support ITC's food innovation team in developing and testing new products.",
    dateOfPost: "2025-05-19"
  },
  {
    id: 46,
    companyName: "Nestle",
    jobTitle: "Nutritionist Intern",
    location: "Delhi",
    stipend: "9000 INR/month",
    requiredSkills: ["Nutrition", "Research", "Excel"],
    internshipType: "Remote",
    description: "Assist in nutritional research and product analysis at Nestle.",
    dateOfPost: "2025-05-18"
  },
  {
    id: 47,
    companyName: "Dabur",
    jobTitle: "Microbiologist Intern",
    location: "Ghaziabad",
    stipend: "9500 INR/month",
    requiredSkills: ["Microbiology", "Research", "Excel"],
    internshipType: "Hybrid",
    description: "Conduct microbiological tests and quality checks for Dabur's products.",
    dateOfPost: "2025-05-17"
  },
  {
    id: 48,
    companyName: "Amul",
    jobTitle: "Dairy Technologist Intern",
    location: "Anand",
    stipend: "8500 INR/month",
    requiredSkills: ["Dairy Tech", "Excel", "Research"],
    internshipType: "On Site",
    description: "Work with Amul's dairy team to improve processing and product quality.",
    dateOfPost: "2025-05-16"
  },
  {
    id: 49,
    companyName: "Parle",
    jobTitle: "Food Safety Intern",
    location: "Mumbai",
    stipend: "8000 INR/month",
    requiredSkills: ["Food Safety", "Research", "Excel"],
    internshipType: "Remote",
    description: "Assist in food safety audits and compliance for Parle's manufacturing units.",
    dateOfPost: "2025-05-15"
  },
  {
    id: 50,
    companyName: "Britannia",
    jobTitle: "Packaging Intern",
    location: "Bangalore",
    stipend: "9000 INR/month",
    requiredSkills: ["Packaging", "Design", "Excel"],
    internshipType: "Hybrid",
    description: "Support Britannia's packaging team in designing and testing new packaging solutions.",
    dateOfPost: "2025-05-14"
  }
];

export default internshipData;
